language: python

python:
  - 3.6

env:
  global:
    # GH_TOKEN to push the docs on Github
    - secure: "YSXBpk7kfoaBq7IKaJBIqwoXeygKW4YCFcdPtjqCTlXnejubxH9Ny0lE4UwuDvV56mg+tyDhFl/4QEO9Wr9vsOHb6bYpOrk+nvZuHH9o3gqxGtsnAc4q8tQGZ+MDKQuB3sJ7tCI4HQTIyXL/QRB4W47g9ygGy4HJwU7k2q8fx0O9C8TbCeKbpQB5Uo/QB4xxEJFElwij8hTMTsd+5r9hJy9q4RCE/yschz7/iPrOPX7ptvbVBq1gc3K+1DpKsnlhJz2J9Kd78cEFum+SdXkDXwOZt4Xk9hbpwXzJRNm1KQIVeuOdQF9yOt8D9FHkXqyqQs4vPaLSK5MudLuDcnMosyk0Y1+pgAdlt8x3SahQhvaaMMzChlksk6zRDzeZdP+jL4Lm87zzXh5/dLF8Xin/jZBiuXIrAodTv1h2Q664mUqgavEbYoTv5CX6/QRoBeJmHs6t0tjBbADAgL5NMtJna9CaDuB080YcnB+NCXm8c6TQUOkmUDvbuJL9BqZkgBvuKaU6DpgA/9Be9zsJeDao1mjxQlVsO9CH8x7zY5npfy37xDLkXPA8kwRxmq08DHoiOLLjQzKC8YK1IWXpe1jTAyQN36gkC6cwlV9OZYYYEk1Gucp0K2OAYXk3ZlmXr1R/gywXZNZ1C/za75gZamXqi/vwCmr2qOiTkQuIRhG6aDg="
    # TX_TOKEN for testing on Transifex
    - secure: "jBJCrb5RRYpepXzCW8LnSMgPJFosc7P6Oid/2o0ejUfC0PvCbq//57r4LzpaZWZsXmf3N1tu4onL2nIdC8k9c2rquhWju7y6k4jrrGAbZCe3LhyPMXZMWxwvqf7tk7JOGrJs7EuuBQn6hw0WwzCmKBKhHhdVckS8RuolaRM7LbLQNZxwrl29CVn+2bTrCipZsQ08KPpfoGOQVUTA0TEAUioXcM4S8srrPJZC6q55oxrI7n6dj7rmmizLjSYzgLnL50YU4v1s+QAnbHsfEFRscbewYXDXx6xnkSR/p1pI65ct8O2PiVNgvkxqgfUBFA3BYJaVo/y+CFdHSFqQKCMnUygUW9H2dwuwoTT4V9ijPQ316rCtN4oua51yFNlv1bjqqJzqLoJ+Te9c3uvQ+NpG3+6Pi2W9kvc4G8BSMg9VBzhLttp//1LHeTQymVpSdiqvtFbVZYl3sIGaTaj+XSue0vXCetyXVnYQ73u+MBXXFXS9TA7C7/7uJvYEp14K2wUZxKvnFGB+r7+1+DeTcqv+c4Lp/q1QDUvCUpFrNi4wHBnScnJ3uBiWmDtWAa8zBsIlf/pt/EY82anaYw0NLhnMEKaoBPSE13XlTdXjOqnmDjsOBaCVGpXJcZPN+oorJCK5lM+2Sts0Qy6d2SCgoOqsTXg9HgpxlICIRS7YtT/LQIQ="
    # PYPI_USER to deploy to PYPi
    - secure: "a3Zf7yPH/MO4SriYoTqYMMxjirolZQ3UwvB3cUIu87TfAh2+NolZPxaIS6Cqj1T7KZtML3eiGwitk/BImhfjRSwu8dHwIXou5dL7JthKlOLvtlk5f9DNIIYGj6RO5YQ9jU2jIbCkPlox32LMSzMHd7CdqiB2cB1S8mpShgRiQMLb1+3PVnHQKT/hAx7fBWHsDKelYPjmO8LllExKf2AprwFKSGgAzxhOOM8YFWtdE0uue2BWUX+Zhrx3nbyRBYjN0Rtt9Wwo2ie1fU68RCb0TFLncn1HyxKzaZYmJfnDmo3wMl1G1svwpxMjVWPbGJnl6Oysxm6UPjV+6swC3PmfZ6mfev87q8SMHS+p2L3YOetQVUF+sulfud4E2uDSUynMgd/C+4NhJcFIoLWOh5lieRafgRcSGqdOY6wkJwGnxndWuOy9IjqzDADS+ayw0F5Gz7grpJBcsRnZMfVa6fbEa7wWWCshSaOkITRLIvz5VrSq759rHPX1AfS+jO3su4EhHL/Qv/3aOzuaVoU6ePIJBbZIhG6zqc+2o72KaHYIGFcfkUzFu6FTxsy03qbjUkPOLnhJZh8751RroX0pNJjE3svmO00o0OirDJ41bSuyT8XZpUfzRDIg7Nn/mAJA2apk40I7XyuCblwBSxzgfdiaRDTW5UhOgPLodmsv4+tLI4o="
    # PYPI_PASSWORD
    - secure: "cIjb5E+umOaFrhn6ryUiG6JVsKeV3W8lvp/0bJQd7I/jXrWEndlYPufzKaEbygJe082wVil8bETU0AWqUYJjKwEFmiirDfSmhEc6ht5nd1UIS36CrcJXGqTdnTQzCo6rPngVS+b9sDZEaO3ezLSz+anmDPQRIs0bp0G1g3kPUPkbKpUgkLTMqFn1HxwlrX92j5UIN5IVKY5ZbqaE54qHwHIFi4zs39ABYy/mM85S3HiVCDiN5gsucKCQnViGuJDQWifiWJz08dhDeaiOr/oOON9rvG8Zy2JEJKrhsqZNcgcwIY3SDLjk6bdbx1pyQY3cDuir0jVmE+SwEtUPprBs0LEM8U6CmxHV9xvUPumxWCNexfSNDupOfOLB0eaWMMjYdNCf7XDd8rLbxrBXNpuTwf36bTyLD7MMN0oH9w8+TPh4IRVNtvqF34Tm8NFVhbY8dXv3kCuIWwVK3G2dYMBXOJ1lX86dKRSzrfohqJSOc1tOUc/E9T7x9XiMSIW4pyVkzHm7KTBr/dsJw4WO9IKJYMS7shkS7H9moUyykhT4TIHOdmgbkecMKHgzHZZABlkhAQbDyexh/FdtCeMbgwj9rkNcPj4ZJuXBCEClBr2NBAWRv6FkvKLS1/3eAOOWtEYF8Pg7gGDwx4oRCTZ+ZGTLajJ/TO+6sfu0Lfc2x/ovGbk="

install: pip install -r requirements.txt

script:
  - nose2 -v
  - ./docs/build_deploy.sh  # TODO: move to deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: ${GH_TOKEN}
    local_dir: ${TRAVIS_BUILD_DIR}/docs/_build/html
    keep_history: false
    target_branch: gh-pages
    on:
      branch: master

  - provider: script
    script:
      -  ./.deploy/deploy_to_pypi.sh
    on:
      branch: master
      tags: true
