language: python

python:
  - 3.6

env:
  global:
    # GH_TOKEN to push the docs on Github
    - secure: "YSXBpk7kfoaBq7IKaJBIqwoXeygKW4YCFcdPtjqCTlXnejubxH9Ny0lE4UwuDvV56mg+tyDhFl/4QEO9Wr9vsOHb6bYpOrk+nvZuHH9o3gqxGtsnAc4q8tQGZ+MDKQuB3sJ7tCI4HQTIyXL/QRB4W47g9ygGy4HJwU7k2q8fx0O9C8TbCeKbpQB5Uo/QB4xxEJFElwij8hTMTsd+5r9hJy9q4RCE/yschz7/iPrOPX7ptvbVBq1gc3K+1DpKsnlhJz2J9Kd78cEFum+SdXkDXwOZt4Xk9hbpwXzJRNm1KQIVeuOdQF9yOt8D9FHkXqyqQs4vPaLSK5MudLuDcnMosyk0Y1+pgAdlt8x3SahQhvaaMMzChlksk6zRDzeZdP+jL4Lm87zzXh5/dLF8Xin/jZBiuXIrAodTv1h2Q664mUqgavEbYoTv5CX6/QRoBeJmHs6t0tjBbADAgL5NMtJna9CaDuB080YcnB+NCXm8c6TQUOkmUDvbuJL9BqZkgBvuKaU6DpgA/9Be9zsJeDao1mjxQlVsO9CH8x7zY5npfy37xDLkXPA8kwRxmq08DHoiOLLjQzKC8YK1IWXpe1jTAyQN36gkC6cwlV9OZYYYEk1Gucp0K2OAYXk3ZlmXr1R/gywXZNZ1C/za75gZamXqi/vwCmr2qOiTkQuIRhG6aDg="
    # TX_TOKEN for testing on Transifex
    - secure: "jBJCrb5RRYpepXzCW8LnSMgPJFosc7P6Oid/2o0ejUfC0PvCbq//57r4LzpaZWZsXmf3N1tu4onL2nIdC8k9c2rquhWju7y6k4jrrGAbZCe3LhyPMXZMWxwvqf7tk7JOGrJs7EuuBQn6hw0WwzCmKBKhHhdVckS8RuolaRM7LbLQNZxwrl29CVn+2bTrCipZsQ08KPpfoGOQVUTA0TEAUioXcM4S8srrPJZC6q55oxrI7n6dj7rmmizLjSYzgLnL50YU4v1s+QAnbHsfEFRscbewYXDXx6xnkSR/p1pI65ct8O2PiVNgvkxqgfUBFA3BYJaVo/y+CFdHSFqQKCMnUygUW9H2dwuwoTT4V9ijPQ316rCtN4oua51yFNlv1bjqqJzqLoJ+Te9c3uvQ+NpG3+6Pi2W9kvc4G8BSMg9VBzhLttp//1LHeTQymVpSdiqvtFbVZYl3sIGaTaj+XSue0vXCetyXVnYQ73u+MBXXFXS9TA7C7/7uJvYEp14K2wUZxKvnFGB+r7+1+DeTcqv+c4Lp/q1QDUvCUpFrNi4wHBnScnJ3uBiWmDtWAa8zBsIlf/pt/EY82anaYw0NLhnMEKaoBPSE13XlTdXjOqnmDjsOBaCVGpXJcZPN+oorJCK5lM+2Sts0Qy6d2SCgoOqsTXg9HgpxlICIRS7YtT/LQIQ="

install: pip install -r requirements.txt

script:
  - nosetests -v
  - ./docs/build_deploy.sh  # TODO: move to deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: ${GH_TOKEN}
    local_dir: ${TRAVIS_BUILD_DIR}/docs/_build/html
    keep_history: true
    target_branch: gh-pages
    on:
      branch: master

  - provider: script
    script:
      -  ./.deploy/deploy_to_pypi.sh
    on:
      branch: master
      tags: true


