language: python

python:
  - 3.6

env:
  global:

install: pip install -r requirements.txt


script:
  - nosetests -v
  - ./docs/build_deploy.sh  # TODO: move to deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: ${GH_TOKEN}
    local_dir: ${TRAVIS_BUILD_DIR}/docs/_build/html
    keep_history: true
    target_branch: gh-pages
    on:
      branch: master

  - provider: script
    script:
      -  ./.deploy/deploy_to_pypi.sh
    on:
      branch: master
      tags: true


