name: test pytransifex

concurrency: testing_environment

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install project requirements
        run: |
          python -m pip install -U -r requirements/base.txt
          python -m pip install -U -r requirements/dev.txt

      - name: Run CI tests
        env:
          organization: ${{ secrets.ORGANIZATION }}
          tx_token: ${{ secrets.TX_TOKEN }}
        run: |
          TX_TOKEN=$tx_token ORGANIZATION=$organization \
            python -m unittest discover -s ./tests -p 'test_*.py'
