name: Test Pytx

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run CI tests
        env:
          organization: ${{ secrets.ORGANIZATION }}
          tx_token: ${{ secrets.TX_TOKEN }}
        run: |
          pip install -r requirements.txt
          TX_TOKEN=$tx_token ORGANIZATION=$organization \
            python -m unittest discover -s ./tests -p 'test_*.py'
