name: test pytransifex

concurrency: testing_environment

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:


jobs:
  tests:
    env:
      TX_ORGANIZATION: ${{ secrets.TX_ORGANIZATION }}
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      # Not using strategy.matrix to create multiple jobs
      # as we do NOT want to test with any form of concurrency
      # to avoid 'race conditions' against Transifex

      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install project requirements
        run: |
          python -m pip install -U -r requirements/base.txt
          python -m pip install -U -r requirements/dev.txt

      - name: Tests
        env:
          TX_ORGANIZATION: ${{ secrets.TX_ORGANIZATION }}
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: nose2 -v

      - uses: mxschmitt/action-tmate@v3
        if: failure()
